apiVersion: apps/v1
kind: Deployment
metadata:
   name: codimdapp
spec:
   replicas: 3
   selector:
     matchLabels:
       app: codimd
   template:
     metadata:
       labels:
         app: codimd
     spec:
       containers:
       - name: codimdapp
         image: hachikoapp/codimd:777
         imagePullPolicy: Always
         command: ["npm"]
         args: ["start"]         
         ports:
         - containerPort: 3000
         env:
         - name: NODE_ENV
           value: production
         - name: CMD_DB_URL
           value: mysql://root:password@timeoff-database:3306/timeoffdb