apiVersion: v1
kind: Service
metadata:
   name: codimdapp
   labels:
    run: codimd
spec:
   ports:
   - name: http
     port: 80
     targetPort: 3000
     protocol: TCP
   - name: https
     port: 443
     targetPort: 3000
     protocol: TCP
   type: LoadBalancer
   selector:
     app: codimd