version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing app dependencies...
      - echo Run "yarn install"...
      - yarn install
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7) 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Logging in to Docker HUB...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Docker image...
      - docker build -t $DOCKER_LOGIN/codimd:$ENV -t $DOCKER_LOGIN/codimd:$COMMIT_HASH .
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Pushing the Docker image...
      - docker push $DOCKER_LOGIN/codimd