version: "1.0"

stages:
  - "clone"
  - "build"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "williammunozr/codimd"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "hachikoapp/codimd"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    registry: dockerhub

  push:
    title: "Pushing Docker Image"
    type: push
    image_name: "hachikoapp/codimd"
    tag: "latest"
    stage: "push" 
    registry: dockerhub
    candidate: ${{build}}

